# Generated by Django 4.1.7 on 2023-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_en_stock',
            field=models.IntegerField(default=0),
        ),
    ]
